### ISSUE TITLE
scale bar on correlogram

### ISSUE THREAD

**Issue by kkatlowitz** [LongLabGit/Clustering#3]
time and percentage axes

also to dynamically scroll through bins and width would be awesome

**Comment by LongLabGit** [comment]
rtfm:
:cb X - set correlogram bin size to X
:cw X - set correlogram window width to X

with less attitude:
I stumbled across a much better, hands-on documentation of template-gui here:
https://github.com/kwikteam/phy-contrib/blob/master/docs/template-gui.md
There I found the above mentioned shortcuts that easily allow doing what this feature request wants just using the keyboard (no stupid clicking like currently required)
